import{useSyncExternalStore}from"react";import type{Item}from"./types";
export type Bom={id:string;code:string;parentItemId:string;version:string;baseQty:number;active:boolean;lines:{itemId:string;qty:number;uom:string}[]};
export type Lot={id:string;lotNo:string;itemId:string;location:string;qty:number;status:string;source:string};
export type WorkOrder={id:string;no:string;bomId:string;productId:string;target:number;actual:number;reject:number;status:string;due:string;productionLot:string};
export type MaterialRequest={id:string;no:string;woId:string;status:string;lines:{itemId:string;required:number;requested:number;issued:number;uom:string}[]};
export type MaterialIssue={id:string;no:string;mrId:string;woId:string;status:string;lines:{itemId:string;lotId:string;qty:number;uom:string}[]};
export type ProductionResult={id:string;no:string;woId:string;fgLotId:string;good:number;reject:number;status:string};
export type Transfer={id:string;no:string;sourceType:"MATERIAL"|"FINISHED_GOODS";sourceId:string;woId:string;from:string;to:string;status:"WAITING_RECEIVE"|"RECEIVED";lines:{itemId:string;lotId:string;qty:number;uom:string}[]};
export type Ledger={id:string;no:string;type:string;itemId:string;lotId:string;qty:number;direction:"IN"|"OUT";reference:string;status:string;location:string};
export type Audit={id:string;action:string;reference:string;actor:string;time:string};
export type DemoDatabase={items:Item[];boms:Bom[];lots:Lot[];orders:WorkOrder[];requests:MaterialRequest[];issues:MaterialIssue[];results:ProductionResult[];transfers:Transfer[];ledger:Ledger[];audit:Audit[]};
const seed:DemoDatabase={items:[{id:"1",sku:"RM-ABS-001",name:"ABS Resin Black",type:"RAW MATERIAL",category:"Plastic Resin",uom:"KG",minimumStock:350,stock:1240,lots:1,active:true},{id:"2",sku:"RM-LED-014",name:"LED Module 12V",type:"RAW MATERIAL",category:"Electrical",uom:"PCS",minimumStock:300,stock:500,lots:1,active:true},{id:"3",sku:"RM-LENS-008",name:"Clear Lens Type B",type:"RAW MATERIAL",category:"Lens",uom:"PCS",minimumStock:120,stock:500,lots:1,active:true},{id:"5",sku:"FG-RL-220",name:"Rear Combination Lamp",type:"FINISHED GOODS",category:"Rear Lamp",uom:"PCS",minimumStock:240,stock:0,lots:0,active:true}],boms:[{id:"bom-1",code:"BOM-FG-RL-220-V1",parentItemId:"5",version:"V1",baseQty:1,active:true,lines:[{itemId:"1",qty:.24,uom:"KG"},{itemId:"2",qty:1,uom:"PCS"},{itemId:"3",qty:1,uom:"PCS"}]}],lots:[{id:"lot-abs",lotNo:"RM-260911-ABS",itemId:"1",location:"WH-RM",qty:1240,status:"AVAILABLE",source:"RCV-20260911-0001"},{id:"lot-led",lotNo:"RM-260911-LED",itemId:"2",location:"WH-RM",qty:500,status:"AVAILABLE",source:"RCV-20260911-0002"},{id:"lot-lens",lotNo:"RM-260911-LNS",itemId:"3",location:"WH-RM",qty:500,status:"AVAILABLE",source:"RCV-20260911-0003"}],orders:[{id:"wo-1",no:"PO-20260911-0001",bomId:"bom-1",productId:"5",target:200,actual:0,reject:0,status:"RELEASED",due:"Shift 1",productionLot:"LOT-PROD-260911-A"}],requests:[],issues:[],results:[],transfers:[],ledger:[],audit:[{id:"a0",action:"RELEASE PRODUCTION ORDER",reference:"PO-20260911-0001",actor:"PPC-1001",time:"11 Sep · 07:30"}]};
const key="msc-erp-flow-v1";let current:DemoDatabase=(()=>{try{const x=JSON.parse(localStorage.getItem(key)||"");return x?.transfers?x:structuredClone(seed)}catch{return structuredClone(seed)}})();const listeners=new Set<()=>void>();
function commit(next:DemoDatabase){const items=next.items.map(i=>({...i,stock:next.lots.filter(l=>l.itemId===i.id).reduce((n,l)=>n+l.qty,0),lots:next.lots.filter(l=>l.itemId===i.id&&l.qty>0).length}));current={...next,items};localStorage.setItem(key,JSON.stringify(current));listeners.forEach(f=>f())}
const seq=(p:string,n:number)=>`${p}-20260911-${String(n+1).padStart(4,"0")}`,log=(db:DemoDatabase,action:string,reference:string,actor:string):Audit[]=>[{id:crypto.randomUUID(),action,reference,actor,time:"Just now"},...db.audit];
export function useDemoDatabase(){const db=useSyncExternalStore(fn=>{listeners.add(fn);return()=>listeners.delete(fn)},()=>current);
const saveItem=(data:Item)=>{const items=current.items.some(x=>x.id===data.id)?current.items.map(x=>x.id===data.id?data:x):[data,...current.items];commit({...current,items,audit:log(current,"SAVE ITEM",data.sku,"ADMIN")})};
const createOrder=()=>{const no=seq("PO",current.orders.length),o:WorkOrder={id:crypto.randomUUID(),no,bomId:"bom-1",productId:"5",target:300,actual:0,reject:0,status:"DRAFT",due:"Next shift",productionLot:`LOT-PROD-${no.slice(-4)}`};commit({...current,orders:[o,...current.orders],audit:log(current,"CREATE PRODUCTION ORDER",no,"PPC")})};
const releaseOrder=(woId:string)=>{const o=current.orders.find(x=>x.id===woId);if(!o||o.status!=="DRAFT")return;commit({...current,orders:current.orders.map(x=>x.id===woId?{...x,status:"RELEASED"}:x),audit:log(current,"RELEASE PRODUCTION ORDER",o.no,"PPC")})};
const createRequest=(woId:string)=>{if(current.requests.some(x=>x.woId===woId&&x.status!=="CLOSED"))return;const wo=current.orders.find(x=>x.id===woId),bom=wo&&current.boms.find(x=>x.id===wo.bomId);if(!wo||wo.status!=="RELEASED"||!bom)return;const r:MaterialRequest={id:crypto.randomUUID(),no:seq("MR",current.requests.length),woId,status:"RELEASED",lines:bom.lines.map(x=>({itemId:x.itemId,required:x.qty*wo.target,requested:x.qty*wo.target,issued:0,uom:x.uom}))};commit({...current,requests:[r,...current.requests],audit:log(current,"RELEASE MATERIAL REQUEST",r.no,"WAREHOUSE")})};
const issueRemaining=(mrId:string)=>{const mr=current.requests.find(x=>x.id===mrId);if(!mr||!['RELEASED','PARTIALLY ISSUED'].includes(mr.status))return;const lines=mr.lines.flatMap(line=>{const lot=current.lots.find(x=>x.itemId===line.itemId&&x.location==="WH-RM"&&x.qty>0),qty=Math.min(line.requested-line.issued,lot?.qty||0);return lot&&qty>0?[{itemId:line.itemId,lotId:lot.id,qty,uom:line.uom}]:[]});if(!lines.length)return;const no=seq("MI",current.issues.length),issue:MaterialIssue={id:crypto.randomUUID(),no,mrId,woId:mr.woId,status:"POSTED",lines},transfer:Transfer={id:crypto.randomUUID(),no:seq("TRF",current.transfers.length),sourceType:"MATERIAL",sourceId:no,woId:mr.woId,from:"WH-RM",to:"PROD-STAGING",status:"WAITING_RECEIVE",lines};const lots=current.lots.map(l=>{const q=lines.filter(x=>x.lotId===l.id).reduce((n,x)=>n+x.qty,0);return q?{...l,qty:l.qty-q}:l}),requests=current.requests.map(r=>r.id!==mrId?r:{...r,status:r.lines.every(x=>x.issued+(lines.find(y=>y.itemId===x.itemId)?.qty||0)>=x.requested)?"ISSUED":"PARTIALLY ISSUED",lines:r.lines.map(x=>({...x,issued:x.issued+(lines.find(y=>y.itemId===x.itemId)?.qty||0)}))}),ledger=[...lines.map((x,i):Ledger=>({id:crypto.randomUUID(),no,type:"MATERIAL TRANSFER OUT",itemId:x.itemId,lotId:x.lotId,qty:x.qty,direction:"OUT",reference:transfer.no,status:"POSTED",location:"WH-RM"})),...current.ledger];commit({...current,lots,requests,issues:[issue,...current.issues],transfers:[transfer,...current.transfers],ledger,audit:log(current,"POST & PREPARE MATERIAL",transfer.no,"WAREHOUSE")})};
const receiveTransfer=(transferId:string,actor="PRODUCTION")=>{const t=current.transfers.find(x=>x.id===transferId);if(!t||t.status!=="WAITING_RECEIVE")return;let lots=[...current.lots];const ledger:Ledger[]=[];for(const line of t.lines){const src=lots.find(x=>x.id===line.lotId)!;const id=crypto.randomUUID();lots=[{...src,id,location:t.to,qty:line.qty,status:"AVAILABLE",source:t.no},...lots];ledger.push({id:crypto.randomUUID(),no:t.no,type:"TRANSFER RECEIVE",itemId:line.itemId,lotId:id,qty:line.qty,direction:"IN",reference:t.woId,status:"POSTED",location:t.to})}const transfers=current.transfers.map(x=>x.id===transferId?{...x,status:"RECEIVED" as const}:x),orders=current.orders.map(x=>x.id===t.woId&&t.sourceType==="MATERIAL"?{...x,status:"READY FOR PRODUCTION"}:x);commit({...current,lots,transfers,orders,ledger:[...ledger,...current.ledger],audit:log(current,"SCAN RECEIVE TRANSFER",t.no,actor)})};
const postResult=(woId:string)=>{const wo=current.orders.find(x=>x.id===woId),material=current.transfers.find(x=>x.woId===woId&&x.sourceType==="MATERIAL"&&x.status==="RECEIVED");if(!wo||!material||!['READY FOR PRODUCTION','IN PRODUCTION'].includes(wo.status))return;const good=wo.target-2,reject=2,no=seq("PRD",current.results.length),lot:Lot={id:crypto.randomUUID(),lotNo:wo.productionLot,itemId:wo.productId,location:"PROD-FG",qty:good,status:"WAITING_TRANSFER",source:no},result:ProductionResult={id:crypto.randomUUID(),no,woId,fgLotId:lot.id,good,reject,status:"POSTED"},transfer:Transfer={id:crypto.randomUUID(),no:seq("TRF",current.transfers.length),sourceType:"FINISHED_GOODS",sourceId:no,woId,from:"PROD-FG",to:"WH-FG/DELIVERY",status:"WAITING_RECEIVE",lines:[{itemId:wo.productId,lotId:lot.id,qty:good,uom:"PCS"}]};commit({...current,orders:current.orders.map(x=>x.id===woId?{...x,actual:good,reject,status:"COMPLETED - WAITING DELIVERY"}:x),lots:[lot,...current.lots],results:[result,...current.results],transfers:[transfer,...current.transfers],ledger:[{id:crypto.randomUUID(),no,type:"PRODUCTION RECEIPT",itemId:wo.productId,lotId:lot.id,qty:good,direction:"IN",reference:woId,status:"POSTED",location:"PROD-FG"},...current.ledger],audit:log(current,"POST PRODUCTION RESULT",no,"PRODUCTION")})};
const receiveFinishedGoods=(transferId:string)=>{const t=current.transfers.find(x=>x.id===transferId);if(!t||t.sourceType!=="FINISHED_GOODS"||t.status!=="WAITING_RECEIVE")return;const src=current.lots.find(x=>x.id===t.lines[0].lotId)!;const lots=current.lots.map(x=>x.id===src.id?{...x,location:"WH-FG/DELIVERY",status:"RELEASED"}:x),transfers=current.transfers.map(x=>x.id===transferId?{...x,status:"RECEIVED" as const}:x);commit({...current,lots,transfers,ledger:[{id:crypto.randomUUID(),no:t.no,type:"FG DELIVERY RECEIVE",itemId:src.itemId,lotId:src.id,qty:t.lines[0].qty,direction:"IN",reference:t.woId,status:"POSTED",location:"WH-FG/DELIVERY"},...current.ledger],audit:log(current,"SCAN RECEIVE FINISHED GOODS",t.no,"DELIVERY")})};
const receive=()=>{};const reset=()=>commit(structuredClone(seed));return{db,saveItem,createOrder,releaseOrder,createRequest,issueRemaining,receiveTransfer,postResult,receiveFinishedGoods,receive,reset}}
