import {useSyncExternalStore} from "react";
import type {Item} from "./types";

export type Bom={id:string;code:string;parentItemId:string;version:string;baseQty:number;active:boolean;lines:{itemId:string;qty:number;uom:string}[]};
export type Lot={id:string;lotNo:string;itemId:string;location:string;qty:number;status:string;source:string};
export type WorkOrder={id:string;no:string;bomId:string;productId:string;target:number;actual:number;reject:number;status:string;due:string};
export type MaterialRequest={id:string;no:string;woId:string;status:string;lines:{itemId:string;required:number;requested:number;issued:number;uom:string}[]};
export type MaterialIssue={id:string;no:string;mrId:string;woId:string;status:string;lines:{itemId:string;lotId:string;qty:number;uom:string}[]};
export type ProductionResult={id:string;no:string;woId:string;fgLotId:string;good:number;reject:number;status:string};
export type Ledger={id:string;no:string;type:string;itemId:string;lotId:string;qty:number;direction:"IN"|"OUT";reference:string;status:string};
export type Audit={id:string;action:string;reference:string;actor:string;time:string};
export type DemoDatabase={items:Item[];boms:Bom[];lots:Lot[];orders:WorkOrder[];requests:MaterialRequest[];issues:MaterialIssue[];results:ProductionResult[];ledger:Ledger[];audit:Audit[]};

const seed:DemoDatabase={
 items:[{id:"1",sku:"RM-ABS-001",name:"ABS Resin Black",type:"RAW MATERIAL",category:"Plastic Resin",uom:"KG",minimumStock:350,stock:1240,lots:1,active:true},{id:"2",sku:"RM-LED-014",name:"LED Module 12V",type:"RAW MATERIAL",category:"Electrical",uom:"PCS",minimumStock:300,stock:286,lots:1,active:true},{id:"3",sku:"RM-LENS-008",name:"Clear Lens Type B",type:"RAW MATERIAL",category:"Lens",uom:"PCS",minimumStock:120,stock:94,lots:1,active:true},{id:"4",sku:"WIP-HSG-002",name:"Rear Lamp Housing",type:"WIP",category:"Semi Finished",uom:"PCS",minimumStock:150,stock:418,lots:1,active:true},{id:"5",sku:"FG-RL-220",name:"Rear Combination Lamp",type:"FINISHED GOODS",category:"Rear Lamp",uom:"PCS",minimumStock:240,stock:672,lots:1,active:true}],
 boms:[{id:"bom-1",code:"BOM-FG-RL-220-V1",parentItemId:"5",version:"V1",baseQty:1,active:true,lines:[{itemId:"1",qty:.24,uom:"KG"},{itemId:"2",qty:1,uom:"PCS"},{itemId:"3",qty:1,uom:"PCS"}]}],
 lots:[{id:"lot-abs",lotNo:"RM-260907-A",itemId:"1",location:"WH-RM",qty:1240,status:"AVAILABLE",source:"RCV-20260911-0001"},{id:"lot-led",lotNo:"LED-260911-B",itemId:"2",location:"WH-RM",qty:286,status:"AVAILABLE",source:"RCV-20260911-0002"},{id:"lot-lens",lotNo:"LNS-260828-A",itemId:"3",location:"WH-RM",qty:94,status:"AVAILABLE",source:"RCV-20260828-0001"},{id:"lot-wip",lotNo:"WIP-260910-A",itemId:"4",location:"WH-WIP",qty:418,status:"AVAILABLE",source:"PRD-20260910-0002"},{id:"lot-fg",lotNo:"FG-20260911-0003",itemId:"5",location:"WH-FG",qty:672,status:"RELEASED",source:"PRD-20260911-0003"}],
 orders:[{id:"wo-1",no:"WO-20260911-0001",bomId:"bom-1",productId:"5",target:200,actual:196,reject:4,status:"IN PRODUCTION",due:"Shift 1"},{id:"wo-2",no:"WO-20260912-0001",bomId:"bom-1",productId:"5",target:300,actual:0,reject:0,status:"RELEASED",due:"Tomorrow"}],
 requests:[{id:"mr-0",no:"MR-20260911-0001",woId:"wo-1",status:"ISSUED",lines:[{itemId:"1",required:48,requested:48,issued:48,uom:"KG"},{itemId:"2",required:200,requested:200,issued:200,uom:"PCS"},{itemId:"3",required:200,requested:200,issued:200,uom:"PCS"}]},{id:"mr-1",no:"MR-20260912-0001",woId:"wo-2",status:"PARTIALLY ISSUED",lines:[{itemId:"1",required:72,requested:72,issued:24,uom:"KG"},{itemId:"2",required:300,requested:300,issued:0,uom:"PCS"},{itemId:"3",required:300,requested:300,issued:0,uom:"PCS"}]}],
 issues:[{id:"mi-0",no:"MI-20260911-0001",mrId:"mr-0",woId:"wo-1",status:"POSTED",lines:[{itemId:"1",lotId:"lot-abs",qty:48,uom:"KG"},{itemId:"2",lotId:"lot-led",qty:200,uom:"PCS"},{itemId:"3",lotId:"lot-lens",qty:200,uom:"PCS"}]},{id:"mi-1",no:"MI-20260912-0001",mrId:"mr-1",woId:"wo-2",status:"POSTED",lines:[{itemId:"1",lotId:"lot-abs",qty:24,uom:"KG"}]}],
 results:[{id:"prd-1",no:"PRD-20260911-0003",woId:"wo-1",fgLotId:"lot-fg",good:196,reject:4,status:"POSTED"}],
 ledger:[{id:"l0",no:"MI-20260911-0001",type:"MATERIAL ISSUE",itemId:"1",lotId:"lot-abs",qty:48,direction:"OUT",reference:"wo-1",status:"POSTED"},{id:"l1",no:"MI-20260912-0001",type:"MATERIAL ISSUE",itemId:"1",lotId:"lot-abs",qty:24,direction:"OUT",reference:"wo-2",status:"POSTED"},{id:"l2",no:"PRD-20260911-0003",type:"FG RECEIPT",itemId:"5",lotId:"lot-fg",qty:196,direction:"IN",reference:"wo-1",status:"POSTED"}],
 audit:[{id:"a1",action:"POST MATERIAL ISSUE",reference:"MI-20260912-0001",actor:"WH-2001",time:"12 Sep · 08:42"},{id:"a2",action:"POST PRODUCTION RESULT",reference:"PRD-20260911-0003",actor:"PROD-1001",time:"11 Sep · 10:18"}]
};
const key="msc-linked-demo-v2";let current:DemoDatabase=(()=>{try{return JSON.parse(localStorage.getItem(key)||"") as DemoDatabase}catch{return structuredClone(seed)}})();const listeners=new Set<()=>void>();
function commit(next:DemoDatabase){const items=next.items.map(item=>({...item,stock:next.lots.filter(l=>l.itemId===item.id).reduce((n,l)=>n+l.qty,0),lots:next.lots.filter(l=>l.itemId===item.id&&l.qty>0).length}));current={...next,items};localStorage.setItem(key,JSON.stringify(current));listeners.forEach(fn=>fn())}
const sequence=(prefix:string,count:number)=>`${prefix}-20260912-${String(count+1).padStart(4,"0")}`;
const log=(db:DemoDatabase,action:string,reference:string,actor:string):Audit[]=>[{id:crypto.randomUUID(),action,reference,actor,time:"Just now"},...db.audit];
export function useDemoDatabase(){const db=useSyncExternalStore(fn=>{listeners.add(fn);return()=>listeners.delete(fn)},()=>current);
 const saveItem=(data:Item)=>{const items=current.items.some(x=>x.id===data.id)?current.items.map(x=>x.id===data.id?data:x):[data,...current.items];commit({...current,items,audit:log(current,"SAVE ITEM",data.sku,"ADMIN")})};
 const createRequest=(woId:string)=>{if(current.requests.some(x=>x.woId===woId&&x.status!=="CLOSED"))return current.requests.find(x=>x.woId===woId)!;const wo=current.orders.find(x=>x.id===woId)!,bom=current.boms.find(x=>x.id===wo.bomId)!;const request:MaterialRequest={id:crypto.randomUUID(),no:sequence("MR",current.requests.length),woId,status:"REQUESTED",lines:bom.lines.map(x=>({itemId:x.itemId,required:x.qty*wo.target,requested:x.qty*wo.target,issued:0,uom:x.uom}))};commit({...current,requests:[request,...current.requests],audit:log(current,"CREATE MATERIAL REQUEST",request.no,"PRODUCTION")});return request};
 const issueRemaining=(mrId:string)=>{const mr=current.requests.find(x=>x.id===mrId)!;const lines=mr.lines.flatMap(line=>{const lot=current.lots.find(x=>x.itemId===line.itemId&&x.qty>0),qty=Math.min(line.requested-line.issued,lot?.qty||0);return lot&&qty>0?[{itemId:line.itemId,lotId:lot.id,qty,uom:line.uom}]:[]});if(!lines.length)return;const issue:MaterialIssue={id:crypto.randomUUID(),no:sequence("MI",current.issues.length),mrId,woId:mr.woId,status:"POSTED",lines};const lots=current.lots.map(l=>{const used=lines.filter(x=>x.lotId===l.id).reduce((n,x)=>n+x.qty,0);return used?{...l,qty:l.qty-used}:l});const requests=current.requests.map(r=>r.id!==mrId?r:{...r,status:"ISSUED",lines:r.lines.map(x=>({...x,issued:x.issued+(lines.find(y=>y.itemId===x.itemId)?.qty||0)}))});const ledger=[...lines.map((x,i):Ledger=>({id:crypto.randomUUID(),no:issue.no,type:"MATERIAL ISSUE",itemId:x.itemId,lotId:x.lotId,qty:x.qty,direction:"OUT",reference:mr.woId,status:"POSTED"})),...current.ledger];commit({...current,lots,requests,issues:[issue,...current.issues],ledger,audit:log(current,"POST MATERIAL ISSUE",issue.no,"WAREHOUSE")})};
 const postResult=(woId:string)=>{const wo=current.orders.find(x=>x.id===woId)!,remaining=wo.target-wo.actual;if(remaining<=0)return;const good=Math.max(0,remaining-2),reject=remaining-good,no=sequence("PRD",current.results.length),lot:Lot={id:crypto.randomUUID(),lotNo:`FG-${no.slice(4)}`,itemId:wo.productId,location:"WH-FG",qty:good,status:"AVAILABLE",source:no},result:ProductionResult={id:crypto.randomUUID(),no,woId,fgLotId:lot.id,good,reject,status:"POSTED"};const orders=current.orders.map(x=>x.id===woId?{...x,actual:x.actual+good,reject:x.reject+reject,status:"COMPLETED"}:x),ledger:Ledger[]=[{id:crypto.randomUUID(),no,type:"FG RECEIPT",itemId:wo.productId,lotId:lot.id,qty:good,direction:"IN",reference:woId,status:"POSTED"},...current.ledger];commit({...current,orders,lots:[lot,...current.lots],results:[result,...current.results],ledger,audit:log(current,"POST PRODUCTION RESULT",no,"PRODUCTION")})};
 const receive=(itemId:string)=>{const item=current.items.find(x=>x.id===itemId)!,no=sequence("RCV",current.ledger.filter(x=>x.type==="RECEIVING").length),lot:Lot={id:crypto.randomUUID(),lotNo:`${item.sku}-LOT-${current.lots.length+1}`,itemId,location:item.type==="FINISHED GOODS"?"WH-FG":"WH-RM",qty:100,status:"AVAILABLE",source:no},entry:Ledger={id:crypto.randomUUID(),no,type:"RECEIVING",itemId,lotId:lot.id,qty:100,direction:"IN",reference:no,status:"POSTED"};commit({...current,lots:[lot,...current.lots],ledger:[entry,...current.ledger],audit:log(current,"POST RECEIVING",no,"WAREHOUSE")})};
 const reset=()=>commit(structuredClone(seed));return{db,saveItem,createRequest,issueRemaining,postResult,receive,reset};}
