export type Role='PPC'|'WAREHOUSE'|'PRODUCTION'|'DELIVERY'|'SUPERVISOR'|'MANAGER'|'ADMIN';
export type POStatus='DRAFT'|'RELEASED'|'MATERIAL PREPARED'|'READY FOR PRODUCTION'|'COMPLETED'|'DELIVERED';
export type TransferStatus='WAITING RECEIVE'|'RECEIVED';
export interface Item{code:string;name:string;type:'RM'|'FG';uom:string}
export interface BomLine{item:string;qty:number}
export interface PO{no:string;product:string;target:number;productionLot:string;status:POStatus;createdBy:string}
export interface MR{no:string;po:string;status:'RELEASED'|'ISSUED';lines:{item:string;required:number;lot?:string}[]}
export interface Transfer{no:string;po:string;kind:'MATERIAL'|'FG';from:string;to:string;status:TransferStatus;lines:{item:string;lot:string;qty:number}[]}
export interface Result{no:string;po:string;lot:string;good:number;reject:number}
export interface Ledger{no:string;ref:string;item:string;lot:string;qty:number;direction:'IN'|'OUT';location:string}
export interface Audit{time:string;actor:string;event:string;ref:string}
export interface DB{items:Item[];bom:BomLine[];po:PO[];mr:MR[];transfers:Transfer[];results:Result[];ledger:Ledger[];audit:Audit[]}
const seed:DB={items:[{code:'RM-ABS-01',name:'ABS Resin Black',type:'RM',uom:'KG'},{code:'RM-LED-01',name:'LED Module',type:'RM',uom:'PCS'},{code:'RM-LENS-01',name:'Rear Lamp Lens',type:'RM',uom:'PCS'},{code:'FG-RCL-220',name:'Rear Combination Lamp',type:'FG',uom:'PCS'}],bom:[{item:'RM-ABS-01',qty:.18},{item:'RM-LED-01',qty:1},{item:'RM-LENS-01',qty:1}],po:[],mr:[],transfers:[],results:[],ledger:[{no:'LED-0001',ref:'OPENING',item:'RM-ABS-01',lot:'ABS-260901-A',qty:500,direction:'IN',location:'WH-RM'},{no:'LED-0002',ref:'OPENING',item:'RM-LED-01',lot:'LED-260901-A',qty:1000,direction:'IN',location:'WH-RM'},{no:'LED-0003',ref:'OPENING',item:'RM-LENS-01',lot:'LENS-260901-A',qty:1000,direction:'IN',location:'WH-RM'}],audit:[]};
const KEY='msc-demo-v2'; const clone=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));
export const load=():DB=>{try{return JSON.parse(localStorage.getItem(KEY)||'')||clone(seed)}catch{return clone(seed)}};
export const save=(db:DB)=>localStorage.setItem(KEY,JSON.stringify(db)); export const reset=()=>{localStorage.removeItem(KEY);return clone(seed)};
const id=(p:string,n:number)=>`${p}-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(n+1).padStart(4,'0')}`;
const log=(d:DB,actor:string,event:string,ref:string)=>d.audit.unshift({time:new Date().toLocaleString(),actor,event,ref});
export function createPO(db:DB){const d=clone(db),no=id('PO',d.po.length);d.po.unshift({no,product:'FG-RCL-220',target:200,productionLot:`FG-${Date.now().toString().slice(-6)}`,status:'DRAFT',createdBy:'PPC'});log(d,'PPC','Created Production Order',no);return d}
export function releasePO(db:DB,no:string){const d=clone(db),p=d.po.find(x=>x.no===no);if(!p||p.status!=='DRAFT')throw Error('Only DRAFT PO can be released');p.status='RELEASED';log(d,'PPC','Released Production Order',no);return d}
export function createMR(db:DB,no:string){const d=clone(db),p=d.po.find(x=>x.no===no);if(!p||p.status!=='RELEASED')throw Error('MR requires a RELEASED PO');if(d.mr.some(x=>x.po===no))throw Error('MR already exists');const mrno=id('MR',d.mr.length);d.mr.unshift({no:mrno,po:no,status:'RELEASED',lines:d.bom.map(b=>({item:b.item,required:+(b.qty*p.target).toFixed(2)}))});log(d,'WAREHOUSE','Created Material Request',mrno);return d}
export function prepare(db:DB,no:string){const d=clone(db),mr=d.mr.find(x=>x.po===no),p=d.po.find(x=>x.no===no);if(!mr||!p)throw Error('Released MR required');if(d.transfers.some(x=>x.po===no&&x.kind==='MATERIAL'))throw Error('Material transfer already posted');const lots:Record<string,string>={'RM-ABS-01':'ABS-260901-A','RM-LED-01':'LED-260901-A','RM-LENS-01':'LENS-260901-A'};mr.lines.forEach(l=>l.lot=lots[l.item]);mr.status='ISSUED';const tr=id('TRF',d.transfers.length);d.transfers.unshift({no:tr,po:no,kind:'MATERIAL',from:'WH-RM',to:'PROD-STAGING',status:'WAITING RECEIVE',lines:mr.lines.map(l=>({item:l.item,lot:l.lot!,qty:l.required}))});mr.lines.forEach(l=>d.ledger.unshift({no:id('LED',d.ledger.length),ref:tr,item:l.item,lot:l.lot!,qty:l.required,direction:'OUT',location:'WH-RM'}));p.status='MATERIAL PREPARED';log(d,'WAREHOUSE','Prepared LOT and posted transfer',tr);return d}
export function receiveMaterial(db:DB,no:string){const d=clone(db),t=d.transfers.find(x=>x.po===no&&x.kind==='MATERIAL'),p=d.po.find(x=>x.no===no);if(!t||!p||t.status!=='WAITING RECEIVE')throw Error('Waiting material transfer required');t.status='RECEIVED';t.lines.forEach(l=>d.ledger.unshift({no:id('LED',d.ledger.length),ref:t.no,item:l.item,lot:l.lot,qty:l.qty,direction:'IN',location:'PROD-STAGING'}));p.status='READY FOR PRODUCTION';log(d,'PRODUCTION','Scan received material',t.no);return d}
export function finish(db:DB,no:string){const d=clone(db),p=d.po.find(x=>x.no===no),mt=d.transfers.find(x=>x.po===no&&x.kind==='MATERIAL');if(!p||p.status!=='READY FOR PRODUCTION'||mt?.status!=='RECEIVED')throw Error('Material must be received first');const good=196,reject=p.target-good,rn=id('PRD',d.results.length);d.results.unshift({no:rn,po:no,lot:p.productionLot,good,reject});d.ledger.unshift({no:id('LED',d.ledger.length),ref:rn,item:p.product,lot:p.productionLot,qty:good,direction:'IN',location:'PROD-FG'});const tr=id('TRF',d.transfers.length);d.transfers.unshift({no:tr,po:no,kind:'FG',from:'PROD-FG',to:'DELIVERY',status:'WAITING RECEIVE',lines:[{item:p.product,lot:p.productionLot,qty:good}]});p.status='COMPLETED';log(d,'PRODUCTION',`Posted result GOOD ${good} / REJECT ${reject}`,rn);return d}
export function receiveFG(db:DB,no:string){const d=clone(db),p=d.po.find(x=>x.no===no),t=d.transfers.find(x=>x.po===no&&x.kind==='FG');if(!p||!t||t.status!=='WAITING RECEIVE')throw Error('Waiting FG transfer required');t.status='RECEIVED';t.lines.forEach(l=>d.ledger.unshift({no:id('LED',d.ledger.length),ref:t.no,item:l.item,lot:l.lot,qty:l.qty,direction:'IN',location:'DELIVERY'}));p.status='DELIVERED';log(d,'DELIVERY','Scan received Finished Goods',t.no);return d}
